<?php
$fh = fopen("../data_codenames.cpp", "w");
fwrite($fh, "#include \"data.hpp\"\r\n\r\n// Generated by DataGenerator\r\n\r\nstd::unordered_map<std::string, std::string> codename_to_english_map = {\r\n");

function addFromExport($name)
{
	global $fh;

	$json = json_decode(file_get_contents("../PublicExport/{$name}_en.json"), true);
	foreach ($json[$name] as $item)
	{
		fwrite($fh, "{\"".$item["uniqueName"]."\", \"".$item["name"]."\"},\r\n");
	}
}

addFromExport("ExportResources");

fwrite($fh, "};\r\n");
